-- Table: public.track

CREATE TABLE IF NOT EXISTS public.track
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    uuid character varying COLLATE pg_catalog."default",
    page character varying COLLATE pg_catalog."default",
    "time" timestamp without time zone,
    CONSTRAINT track_pk PRIMARY KEY (id)
)

TABLESPACE pg_default;

-- Index: track_id_index

CREATE INDEX IF NOT EXISTS track_id_index
    ON public.track USING btree
    (id ASC NULLS LAST)
    TABLESPACE pg_default;