# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:10.18-jessie
          
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Compose
      run: |
        sudo apt install --upgrade docker-compose
        sudo apt install --upgrade docker

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Docker Compose Action
      uses: isbang/compose-action@v1.5.1
